### ISSUE TITLE
Add license information

### ISSUE THREAD

**Issue by vazhnov** [Jana-Marie/anotter-sensor-hub#2]
Hello!

I found this project from https://hackaday.com/2023/02/27/hacker-friendly-and-elegant-air-quality-sensor-hub/

Could you please add information about the license of this repository — is it allowed to copy, change and use the code and PCB files in any purpose?
 It would be great to see any popular open source license.

**Comment by Jana-Marie** [comment]
ooh, yes, thank you! I will add that

**Comment by Jana-Marie** [comment]
Done, it is allowed to copy, change and use the code in any purpose (if I did the licensing correctly ^^). Best, Jana

**Comment by vazhnov** [comment]
CERN-OHL-S-2.0 license — great!
@Jana-Marie, thank you very much!
