### ISSUE TITLE
More info about components

### ISSUE THREAD

**Issue by Dredok** [Jana-Marie/anotter-sensor-hub#3]
Hi Jana, 
thanks for the project, I'd like to make it but my knowledge of electronics is VERY basic. So I see the ESP32, a voltage regulator? and a couple of connectors. The connector is a JST GHR 6P if i'm not mistaken; and a usb-c which I assume is for power and programming the ESP32.

A basic BOM with these components would definitely help n00bs like me!

**Comment by Jana-Marie** [comment]
Oh, yes. I will add that in a bit!

**Comment by jens112131** [comment]
I would also like to build it. Already got the PCB but a BOM would be very helpful.

**Comment by Jana-Marie** [comment]
Sorry for the delay, here is the BOM! https://github.com/Jana-Marie/anotter-sensor-hub/blob/main/BOM.csv
